# -
# Plugin: SnuckMissions
# Version: 1.0-SNAPSHOT
# Autor: SnuckDev
# -

# -
# Mensagens principais
# -

conquista-alcancada: '&a&lYAY! &aVocê alcançou a conquista &b{conquista} &acom sucesso.'

#-
# Configuração das conquistas
# -

menu-principal:
  title: 'Menu de missões'
  blocos-quebrados:
    name: '&eDetonador de blocos'
    posicao: 10
    item: 'DIAMOND_PICKAXE'
    lore:
      - '&f1º Objetivo: &7Quebrar &f1.000 &7blocos de qualquer tipo.'
      - '&f2º Objetivo: &7Quebrar &f2.000 &7blocos de qualquer tipo.'
      - '&f3º Objetivo: &7Quebrar &f3.000 &7blocos de qualquer tipo.'
      - '&f4º Objetivo: &7Quebrar &f4.000 &7blocos de qualquer tipo.'
      - '&f5º Objetivo: &7Quebrar &f5.000 &7blocos de qualquer tipo.'
      - ''
      - '&eClique para ver mais detalhes.'

  blocos-colocados:
    name: '&eColocador de blocos'
    posicao: 12
    item: 'DIRT'
    lore:
      - '&f1º Objetivo: &7Colocar &f1.000 &7blocos de qualquer tipo.'
      - '&f2º Objetivo: &7Colocar &f2.000 &7blocos de qualquer tipo.'
      - '&f3º Objetivo: &7Colocar &f3.000 &7blocos de qualquer tipo.'
      - '&f4º Objetivo: &7Colocar &f4.000 &7blocos de qualquer tipo.'
      - '&f5º Objetivo: &7Colocar &f5.000 &7blocos de qualquer tipo.'
      - ''
      - '&eClique para ver mais detalhes.'

  jogadores-mortos:
    name: '&eAssassino de jogadores'
    posicao: 14
    item: 'DIAMOND_SWORD'
    lore:
      - '&f1º Objetivo: &7Matar &f1.000 &7jogadores.'
      - '&f2º Objetivo: &7Matar &f2.000 &7jogadores.'
      - '&f3º Objetivo: &7Matar &f3.000 &7jogadores.'
      - '&f4º Objetivo: &7Matar &f4.000 &7jogadores.'
      - '&f5º Objetivo: &7Matar &f5.000 &7jogadores.'
      - ''
      - '&eClique para ver mais detalhes.'

  monstros-mortos:
    name: '&eAssassino de monstros'
    posicao: 16
    item: 'MONSTER_EGG'
    lore:
      - '&f1º Objetivo: &7Matar &f1.000 &7monstros de qualquer tipo.'
      - '&f2º Objetivo: &7Matar &f2.000 &7monstros de qualquer tipo.'
      - '&f3º Objetivo: &7Matar &f3.000 &7monstros de qualquer tipo.'
      - '&f4º Objetivo: &7Matar &f4.000 &7monstros de qualquer tipo.'
      - '&f5º Objetivo: &7Matar &f5.000 &7monstros de qualquer tipo.'
      - ''
      - '&eClique para ver mais detalhes.'

# -
# Configuração das conquistas - requisitos
# Recomendo deixar o padrão até eu falar, pois se deixar os valores menores pode dar erro na progressbar.
# -

requisitos:
  colocar-blocos:
    level-1: 1000 # O tanto de jogadores para alcançar a conquista 1
    level-2: 2000 # O tanto de jogadores para alcançar a conquista 2
    level-3: 3000 # O tanto de jogadores para alcançar a conquista 3
    level-4: 4000 # O tanto de jogadores para alcançar a conquista 4
    level-5: 5000 # O tanto de jogadores para alcançar a conquista 5

  quebrar-blocos:
    level-1: 1000 # O tanto de jogadores para alcançar a conquista 1
    level-2: 2000 # O tanto de jogadores para alcançar a conquista 2
    level-3: 3000 # O tanto de jogadores para alcançar a conquista 3
    level-4: 4000 # O tanto de jogadores para alcançar a conquista 4
    level-5: 5000 # O tanto de jogadores para alcançar a conquista 5

  matar-monstros:
    level-1: 1000 # O tanto de jogadores para alcançar a conquista 1
    level-2: 2000 # O tanto de jogadores para alcançar a conquista 2
    level-3: 3000 # O tanto de jogadores para alcançar a conquista 3
    level-4: 4000 # O tanto de jogadores para alcançar a conquista 4
    level-5: 5000 # O tanto de jogadores para alcançar a conquista 5

  matar-jogadores:
    level-1: 1000 # O tanto de jogadores para alcançar a conquista 1
    level-2: 2000 # O tanto de jogadores para alcançar a conquista 2
    level-3: 3000 # O tanto de jogadores para alcançar a conquista 3
    level-4: 4000 # O tanto de jogadores para alcançar a conquista 4
    level-5: 5000 # O tanto de jogadores para alcançar a conquista 5